#!/usr/bin/env python3
"""
Helper script to set up the backend .env file with proper Supabase credentials
"""

import os
from pathlib import Path

print("=" * 80)
print("🔧 BACKEND ENVIRONMENT SETUP HELPER")
print("=" * 80)

print("\nThis script will help you create a proper .env file for the Python backend.")
print("\n⚠️  IMPORTANT: The backend needs the SERVICE ROLE KEY, not the anon key!")

# Check if .env already exists
env_path = Path(__file__).resolve().parent / '.env'
if env_path.exists():
    print(f"\n⚠️  Warning: {env_path} already exists!")
    response = input("Do you want to overwrite it? (y/N): ").lower()
    if response != 'y':
        print("Aborting...")
        exit(0)

# Get Supabase URL
print("\n📋 Step 1: Supabase URL")
print("This is the same for both frontend and backend")
print("Example: https://yourproject.supabase.co")
supabase_url = input("Enter your Supabase URL: ").strip()

# Get Service Role Key
print("\n📋 Step 2: Service Role Key (NOT the anon key!)")
print("⚠️  This is different from the anon key used in frontend!")
print("You can find this in your Supabase dashboard:")
print("  1. Go to Settings > API")
print("  2. Look for 'service_role' under 'Project API keys'")
print("  3. This key is much longer than the anon key")
service_role_key = input("Enter your SERVICE ROLE key: ").strip()

# Validate key length (service role keys are typically longer)
if len(service_role_key) < 100:
    print("\n⚠️  Warning: This key seems short for a service role key.")
    print("Service role keys are typically 200+ characters long.")
    print("Make sure you're not using the anon key by mistake!")
    response = input("Continue anyway? (y/N): ").lower()
    if response != 'y':
        print("Aborting...")
        exit(0)

# Optional: Get other API keys
print("\n📋 Optional: Other API Keys")
youtube_key = input("Enter your YouTube API key (or press Enter to skip): ").strip()
openai_key = input("Enter your OpenAI API key (or press Enter to skip): ").strip()

# Create .env content
env_content = f"""# Backend Environment Configuration
# Generated by setup_backend_env.py

# Supabase Configuration for Backend (Python)
SUPABASE_URL={supabase_url}
SUPABASE_KEY={service_role_key}
SUPABASE_ENABLED=true

# YouTube API Configuration
YOUTUBE_API_KEY={youtube_key}

# OpenAI API Configuration  
OPENAI_API_KEY={openai_key}

# Environment identifier
ENVIRONMENT=production
"""

# Write .env file
try:
    with open(env_path, 'w') as f:
        f.write(env_content)
    print(f"\n✅ Successfully created {env_path}")
    
    # Test the configuration
    print("\n🔍 Testing configuration...")
    from dotenv import load_dotenv
    load_dotenv(env_path)
    
    test_url = os.getenv('SUPABASE_URL')
    test_key = os.getenv('SUPABASE_KEY')
    
    if test_url and test_key:
        print("✅ Environment variables loaded successfully!")
        print(f"   URL: {test_url[:40]}...")
        print(f"   KEY: {test_key[:20]}...{test_key[-10:]}")
    else:
        print("❌ Failed to load environment variables!")
        
except Exception as e:
    print(f"\n❌ Error creating .env file: {e}")
    exit(1)

print("\n" + "=" * 80)
print("✅ SETUP COMPLETE!")
print("=" * 80)
print("\nNext steps:")
print("1. Run: python diagnose_supabase.py")
print("2. If successful, run: python summarize_all.py --limit 5 --verbose")
print("\n⚠️  Remember: NEVER commit the .env file to git!")
print("Make sure .env is in your .gitignore file.")
