# TrendSiam Database Object Manifest
# Version: 1.0.0
# Date: 2025-10-21
# Purpose: Complete inventory of all DB objects for CI/CD validation
# Usage: CI smoke tests compare live DB against this manifest

metadata:
  schema: public
  database_type: PostgreSQL
  supabase_project: TrendSiam
  plan_b_enforced: true  # Frontend reads views only, NOT base tables
  last_updated: 2025-10-21
  manifest_version: 1.0.0

# =====================================================
# BASE TABLES (NO anon access - Plan-B)
# =====================================================
base_tables:
  - name: news_trends
    schema: public
    purpose: Primary news content from YouTube/X
    anon_access: false
    authenticated_access: false
    service_role_access: true
    rls_enabled: true
    columns_sample:
      - id
      - video_id
      - external_id
      - title
      - summary
      - summary_en
      - category
      - platform
      - published_date
      - view_count
      - like_count
      - comment_count
      - popularity_score
      - popularity_score_precise
      - ai_image_url
      - ai_image_prompt
      - growth_rate
      - ai_opinion
      - score_details
  
  - name: stories
    schema: public
    purpose: Story metadata and cross-platform aggregation
    anon_access: false
    authenticated_access: false
    service_role_access: true
    rls_enabled: true
    columns_sample:
      - story_id
      - title
      - platform
      - ai_image_prompt
      - created_at
      - updated_at
  
  - name: snapshots
    schema: public
    purpose: Historical metrics for trending analysis
    anon_access: false
    authenticated_access: false
    service_role_access: true
    rls_enabled: true
    columns_sample:
      - snapshot_id
      - story_id
      - snapshot_date
      - view_count
      - like_count
      - comment_count
      - popularity_score
      - growth_rate
      - reason
      - platform_mentions
  
  - name: system_meta
    schema: public
    purpose: System configuration and metadata
    anon_access: false
    authenticated_access: false
    service_role_access: true
    rls_enabled: true
    columns_sample:
      - key
      - value
      - updated_at
    critical_keys:
      - home_limit
      - top3_max
      - home_freshness_policy
      - home_columns_hash
      - news_last_updated
  
  - name: image_files
    schema: public
    purpose: AI-generated images and metadata
    anon_access: false
    authenticated_access: false
    service_role_access: true
    rls_enabled: true
    columns_sample:
      - id
      - story_id
      - image_url
      - reason
      - is_valid
      - generated_at
  
  - name: weekly_snapshots
    schema: public
    purpose: Weekly report data snapshots
    anon_access: false
    authenticated_access: false
    service_role_access: true
    rls_enabled: true
    columns_sample:
      - snapshot_id
      - range_start
      - range_end
      - built_at
      - status

# =====================================================
# VIEWS (Plan-B: anon CAN read)
# =====================================================
views:
  - name: v_home_news
    schema: public
    purpose: Alias to public_v_home_news for backward compatibility
    anon_access: true
    authenticated_access: true
    service_role_access: true
    rls_enabled: false  # Views don't have RLS, inherit from base tables
    security_invoker: false
    security_barrier: false
    definition_type: alias
    depends_on:
      - public_v_home_news
    used_by:
      - frontend/src/hooks/useSupabaseNews.ts
      - frontend/src/components/news/SupabaseNewsGrid.tsx
      - frontend/src/app/supabase-test/page.tsx
    columns_expected: 26
    created_by_migration: 004_create_v_home_news_alias.sql
  
  - name: public_v_home_news
    schema: public
    purpose: Primary home view with 26-column contract (snapshot-based freshness)
    anon_access: true
    authenticated_access: true
    service_role_access: true
    rls_enabled: false
    security_invoker: false  # DEFINER semantics
    security_barrier: true
    definition_type: complex_query
    depends_on:
      - news_trends
      - stories
      - snapshots
      - system_meta
      - public_v_system_meta
      - public_v_ai_images_latest
    used_by:
      - frontend/src/app/api/home/ping/route.ts
      - frontend/src/app/api/permissions/selfcheck/route.ts
      - frontend/src/app/api/test-plan-b/route.ts
      - frontend/src/app/api/home-rest/route.ts
    columns_expected: 26
    columns_contract:
      - id
      - title
      - summary
      - summary_en
      - category
      - platform
      - channel
      - published_at
      - source_url
      - image_url
      - ai_prompt
      - popularity_score
      - rank
      - is_top3
      - views
      - likes
      - comments
      - growth_rate_value
      - growth_rate_label
      - ai_opinion
      - score_details
      - video_id
      - external_id
      - platform_mentions
      - keywords
      - updated_at
    freshness_policy: 72h primary, 30d fallback
    top3_policy: true  # Only top 3 get AI images/prompts
    created_by_migration: Multiple fixes (see 2025-09-26_fix_public_v_home_news_definer.sql)
  
  - name: public_v_system_meta
    schema: public
    purpose: Safe system config keys (whitelist only)
    anon_access: true
    authenticated_access: true
    service_role_access: true
    rls_enabled: false
    security_invoker: false  # DEFINER semantics
    security_barrier: true
    definition_type: filtered_projection
    depends_on:
      - system_meta
    used_by:
      - public_v_home_news
      - get_public_system_meta RPC
    safe_keys_only:
      - home_freshness_policy
      - home_limit
      - top3_max
      - home_columns_hash
      - news_last_updated
    columns_expected: 3
    columns_contract:
      - key
      - value
      - updated_at
    created_by_migration: 2025-09-26_fix_system_meta_permissions.sql
  
  - name: public_v_weekly_stats
    schema: public
    purpose: KPI dashboard metrics for weekly reports
    anon_access: true
    authenticated_access: true
    service_role_access: true
    rls_enabled: false
    security_invoker: true
    security_barrier: true
    definition_type: simple_projection
    depends_on:
      - weekly_snapshots
    used_by:
      - frontend/src/app/weekly-report/page.tsx
      - frontend/src/app/api/weekly/pdf/route.ts
    columns_expected: 5
    columns_contract:
      - snapshot_id
      - status
      - range_start
      - range_end
      - built_at
    created_by_migration: 2025-08-29_plan_b_complete_setup.sql
  
  - name: public_v_ai_images_latest
    schema: public
    purpose: Top-3 AI image/prompt policy enforcement
    anon_access: true
    authenticated_access: true
    service_role_access: true
    rls_enabled: false
    security_invoker: true
    security_barrier: true
    definition_type: filtered_join
    depends_on:
      - image_files
      - stories
    used_by:
      - public_v_home_news
    top3_only: true
    columns_expected: 5
    columns_contract:
      - story_id
      - image_url
      - reason
      - is_valid
      - generated_at
    created_by_migration: 2025-08-29_plan_b_complete_setup.sql

# =====================================================
# FUNCTIONS (RPC, anon CAN execute)
# =====================================================
functions:
  - name: get_public_home_news
    schema: public
    signature: get_public_home_news(p_limit INTEGER, p_offset INTEGER)
    purpose: Paginated home news RPC fallback
    anon_execute: true
    authenticated_execute: true
    service_role_execute: true
    security: SECURITY DEFINER
    owner: postgres
    language: sql
    stability: STABLE
    search_path: pg_catalog, public
    returns: TABLE (26 columns matching public_v_home_news)
    depends_on:
      - public_v_home_news
    used_by:
      - frontend RPC calls (fallback mechanism)
    created_by_migration: 2025-09-26_fix_public_v_home_news_definer.sql
  
  - name: get_public_system_meta
    schema: public
    signature: get_public_system_meta()
    purpose: Config metadata RPC fallback
    anon_execute: true
    authenticated_execute: true
    service_role_execute: true
    security: SECURITY DEFINER
    owner: postgres
    language: sql
    stability: STABLE
    search_path: pg_catalog, public
    returns: TABLE (key text, value text, updated_at timestamptz)
    depends_on:
      - system_meta
    safe_keys_only:
      - home_freshness_policy
      - home_limit
      - top3_max
      - home_columns_hash
      - news_last_updated
    used_by:
      - frontend RPC calls (fallback mechanism)
    created_by_migration: 2025-09-26_fix_system_meta_permissions.sql
  
  - name: util_has_column
    schema: public
    signature: util_has_column(p_table text, p_column text)
    purpose: Schema introspection utility for safe migrations
    anon_execute: true
    authenticated_execute: true
    service_role_execute: true
    security: SECURITY DEFINER
    owner: postgres
    language: plpgsql
    stability: STABLE
    search_path: pg_catalog, public
    returns: BOOLEAN
    depends_on:
      - information_schema.columns
    used_by:
      - Migration scripts
    created_by_migration: Unknown (pre-existing utility)

# =====================================================
# PERMISSIONS VALIDATION RULES
# =====================================================
validation_rules:
  - rule: anon_cannot_read_base_tables
    check_sql: |
      SELECT COUNT(*) FROM pg_tables t
      WHERE schemaname = 'public'
      AND tablename IN ('news_trends', 'stories', 'snapshots', 'system_meta', 'image_files', 'weekly_snapshots')
      AND has_table_privilege('anon', schemaname||'.'||tablename, 'SELECT');
    expected_result: 0
    severity: CRITICAL
    message: "Plan-B violation: anon can read base tables!"
  
  - rule: anon_can_read_views
    check_sql: |
      SELECT COUNT(*) FROM pg_views v
      WHERE schemaname = 'public'
      AND viewname IN ('v_home_news', 'public_v_home_news', 'public_v_system_meta', 'public_v_weekly_stats', 'public_v_ai_images_latest')
      AND has_table_privilege('anon', schemaname||'.'||viewname, 'SELECT');
    expected_result: 5
    severity: CRITICAL
    message: "anon cannot read required views!"
  
  - rule: anon_can_execute_functions
    check_sql: |
      SELECT COUNT(*) FROM pg_proc p
      JOIN pg_namespace n ON p.pronamespace = n.oid
      WHERE n.nspname = 'public'
      AND p.proname IN ('get_public_home_news', 'get_public_system_meta', 'util_has_column')
      AND has_function_privilege('anon', p.oid, 'EXECUTE');
    expected_result: 3
    severity: CRITICAL
    message: "anon cannot execute required functions!"
  
  - rule: functions_have_secure_search_path
    check_sql: |
      SELECT COUNT(*) FROM pg_proc p
      JOIN pg_namespace n ON p.pronamespace = n.oid
      WHERE n.nspname = 'public'
      AND p.proname IN ('get_public_home_news', 'get_public_system_meta', 'util_has_column')
      AND (proconfig IS NULL OR NOT EXISTS (
        SELECT 1 FROM unnest(proconfig) cfg WHERE cfg LIKE 'search_path=%pg_catalog%'
      ));
    expected_result: 0
    severity: HIGH
    message: "Functions missing secure search_path setting!"
  
  - rule: required_views_exist
    check_sql: |
      SELECT COUNT(*) FROM pg_views
      WHERE schemaname = 'public'
      AND viewname IN ('v_home_news', 'public_v_home_news', 'public_v_system_meta', 'public_v_weekly_stats', 'public_v_ai_images_latest');
    expected_result: 5
    severity: CRITICAL
    message: "Required views missing!"
  
  - rule: base_tables_have_rls
    check_sql: |
      SELECT COUNT(*) FROM pg_tables
      WHERE schemaname = 'public'
      AND tablename IN ('news_trends', 'stories', 'snapshots', 'system_meta', 'image_files', 'weekly_snapshots')
      AND rowsecurity = FALSE;
    expected_result: 0
    severity: HIGH
    message: "Base tables missing RLS!"

# =====================================================
# CI/CD SMOKE TEST SCRIPT (Bash)
# =====================================================
smoke_test_script: |
  #!/bin/bash
  # Run this in CI to validate DB state matches manifest
  
  set -e
  
  echo "🔍 Running DB Object Manifest Validation..."
  
  # Check required views exist
  echo "Checking views..."
  psql $DATABASE_URL -t -c "SELECT COUNT(*) FROM pg_views WHERE schemaname='public' AND viewname IN ('v_home_news', 'public_v_home_news', 'public_v_system_meta', 'public_v_weekly_stats', 'public_v_ai_images_latest');" | grep -q "5" || (echo "❌ Required views missing!" && exit 1)
  
  # Check anon cannot read base tables (Plan-B)
  echo "Checking Plan-B (anon cannot read base tables)..."
  COUNT=$(psql $DATABASE_URL -t -c "SELECT COUNT(*) FROM pg_tables t WHERE schemaname = 'public' AND tablename IN ('news_trends', 'stories', 'snapshots', 'system_meta') AND has_table_privilege('anon', schemaname||'.'||tablename, 'SELECT');")
  [ "$COUNT" -eq 0 ] || (echo "❌ Plan-B violation: anon can read base tables!" && exit 1)
  
  # Check anon CAN read views
  echo "Checking anon view access..."
  COUNT=$(psql $DATABASE_URL -t -c "SELECT COUNT(*) FROM pg_views v WHERE schemaname = 'public' AND viewname LIKE 'public_v_%' AND has_table_privilege('anon', schemaname||'.'||viewname, 'SELECT');")
  [ "$COUNT" -ge 4 ] || (echo "❌ anon cannot read required views!" && exit 1)
  
  # Check functions have secure search_path
  echo "Checking function security..."
  COUNT=$(psql $DATABASE_URL -t -c "SELECT COUNT(*) FROM pg_proc p JOIN pg_namespace n ON p.pronamespace = n.oid WHERE n.nspname = 'public' AND p.proname IN ('get_public_home_news', 'get_public_system_meta', 'util_has_column') AND proconfig IS NOT NULL;")
  [ "$COUNT" -ge 2 ] || (echo "⚠️ Warning: Functions may be missing secure search_path" && exit 0)
  
  echo "✅ All DB object manifest checks passed!"

# =====================================================
# MIGRATION ORDER & DEPENDENCIES
# =====================================================
migration_order:
  - 001_drop_legacy_views.sql
  - 002_enable_rls_demo_seed.sql
  - 003_secure_function_search_paths.sql
  - 004_create_v_home_news_alias.sql

rollback_plan: |
  To rollback to a specific migration:
  1. Run the inverse SQL for that migration
  2. For 004: DROP VIEW public.v_home_news;
  3. For 003: ALTER FUNCTION ... SET search_path = public; (remove pg_catalog prefix)
  4. For 002: ALTER TABLE public.home_demo_seed DISABLE ROW LEVEL SECURITY;
  5. For 001: No rollback needed (legacy views were unused)

# =====================================================
# KNOWN ISSUES & TECH DEBT
# =====================================================
known_issues:
  - issue: Inconsistent view naming (v_home_news vs public_v_home_news)
    severity: MEDIUM
    status: MITIGATED
    mitigation: Created alias view in migration 004
    long_term_fix: Migrate all code to use public_v_home_news consistently
    target_date: 2025-11-21
  
  - issue: Some functions may not have search_path set
    severity: LOW
    status: OPEN
    mitigation: Migration 003 sets it for critical functions
    long_term_fix: Audit all functions and set search_path
    target_date: 2025-11-30
  
  - issue: No automated CI test for DB manifest
    severity: MEDIUM
    status: IN_PROGRESS
    mitigation: Manual verification via SQL queries
    long_term_fix: Add smoke_test_script to GitHub Actions
    target_date: 2025-10-25

# =====================================================
# CHANGE LOG
# =====================================================
changelog:
  - date: 2025-10-21
    author: AI Agent (Cursor)
    changes:
      - Created DB_OBJECT_MANIFEST.yaml
      - Created migration 004_create_v_home_news_alias.sql
      - Documented schema decision (public, not public1)
      - Added Plan-B validation rules
      - Added CI smoke test script
    jira_ticket: N/A
    git_commit: chore/python-hash-and-ci-fix (pending)

# =====================================================
# DOCUMENT METADATA
# =====================================================
document_info:
  format_version: 1.0.0
  last_validated: 2025-10-21
  next_review: 2025-11-21
  owner: TrendSiam Dev Team
  status: ACTIVE
  related_docs:
    - reports/db/SCHEMA_DECISION.md
    - memory-bank/01_security_plan_b.mb
    - memory-bank/02_data_stack_and_schema.mb
    - memory-bank/db_schema_inventory.mb

